openapi: 3.0.0
info:
  title: Catalyst Experience API
  version: 0.0.1

servers:
  - url: http://localhost:8080/api
    description: URL for local development and testing

components:
  parameters:
    basicAuthHeader:
      in: header
      name: Authorization
      description: "Basic Authentication"
      schema:
        type: string
      example: "Basic cm9vdC9yb290"

paths:
  /admin/token:
    parameters:
      - $ref: '#/components/parameters/basicAuthHeader'
    post:
      summary: "create a random 6 to 12 digit alphanumeric token"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              example: "BpLnfg"
        '401':
          description: "Unauthorized"
        '500':
          description: "Internal Server Error"
    get:
      summary: "overview of created tokens"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
              example:
                6vyIBf8RIKPc: "VALID"
                9bGBOhQJ: "DISABLED"
                BLt8zG9SW2N: "EXPIRED"
        '401':
          description: "Unauthorized"
        '500':
          description: "Internal Server Error"

  /admin/token/{token}/disable:
    parameters:
      - $ref: '#/components/parameters/basicAuthHeader'
      - name: token
        in: path
        required: true
        schema:
          type: string
        description: "The token which you wish to recall(disable)"
    post:
      summary: "disable(recall) the given token"
      responses:
        '200':
          description: "OK"
        '404':
          description: "Bad Request"
        '401':
          description: "Unauthorized"
        '500':
          description: "Internal Server Error"

  /login:
    post:
      summary: "login with given token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            example: BjS5gX
      responses:
        '200':
          description: "OK"
        '400':
          description: "Bad Request"
        '500':
          description: "Internal Server Error"